matches = {
  'Huddersfield':  'Huddersfield Town',
  'Middlesbrough':  'Middlesbrough FC',
  'West Ham':  'West Ham United',
  'Tottenham':  'Tottenham Hotspur',
  'Stoke': 'Stoke City',
  'Sunderland':  'Sunderland AFC',
  'Leicester':  'Leicester City',
  'Hull': 'Hull City',
  'Sheffield Utd':  'Sheffield United',
  'Cardiff':  'Cardiff City',
  'Wolves':  'Wolverhampton Wanderers',
  'Swansea':  'Swansea City',
  'Fulham':  'Fulham FC',
  'Brighton': 'Brighton &amp; Hove Albion',
  'Chelsea':  'Chelsea FC',
  'West Brom':  'West Bromwich Albion',
  'Norwich':  'Norwich City',
  'Watford':  'Watford FC',
  'Manchester Utd':  'Manchester United',
  'Newcastle':  'Newcastle United',
  'Brentford':  'Brentford FC',
  'Leeds':  'Leeds United',
  'Arsenal':  'Arsenal FC',
  'Burnley':  'Burnley FC',
  'Southampton':  'Southampton FC',
  'Everton': 'Everton FC',
  'Liverpool':  'Liverpool FC',
  'Bournemouth': 'AFC Bournemouth',
  'Ipswich': 'Ipswich Town',
  'Coventry': 'Coventry City',
  'Barnsley': 'Barnsley FC',
  'Reading': 'Reading FC',
  'Rotherham': 'Rotherham United',
  'Blackpool': 'Blackpool FC',
  'Burton': 'Burton Albion',
  'Peterborough': 'Peterborough United',
  'Sheffield Wed': 'Sheffield Wednesday',
  'Nottingham': 'Nottingham Forest',
  'Blackburn': 'Blackburn Rovers',
  'Luton': 'Luton Town',
  'Preston': 'Preston North End',
  'Charlton': 'Charlton Athletic',
  'Bolton': 'Bolton Wanderers',
  'Wigan': 'Wigan Athletic',
  'Wycombe': 'Wycombe Wanderers',
  'QPR': 'Queens Park Rangers',
  'Birmingham': 'Birmingham City',
  'Millwall': 'Millwall FC',
  'Derby': 'Derby County',
  'Chesterfield': 'Chesterfield FC',
  'Gillingham': 'Gillingham FC',
  'Crewe': 'Crewe Alexandra',
  'Rochdale': 'Rochdale AFC',
  'Oxford Utd': 'Oxford United',
  'Doncaster': 'Doncaster Rovers',
  'Oldham': 'Oldham Athletic',
  'Cheltenham': 'Cheltenham Town',
  'Plymouth': 'Plymouth Argyle',
  'Port Vale': 'Port Vale FC',
  'MK Dons': 'Milton Keynes Dons',
  'Morecambe': 'Morecambe FC',
  'Swindon': 'Swindon Town',
  'Lincoln': 'Lincoln City',
  'Portsmouth': 'Portsmouth FC',
  'Southend': 'Southend United',
  'Walsall': 'Walsall FC',
  'Accrington': 'Accrington Stanley',
  'Scunthorpe': 'Scunthorpe United',
  'Fleetwood': 'Fleetwood Town',
  'Northampton': 'Northampton Town',
  'Tranmere': 'Tranmere Rovers',
  'Cambridge Utd': 'Cambridge United',
  'Shrewsbury': 'Shrewsbury Town',
  'Bury': 'Bury FC',
  'Exeter': 'Exeter City',
  'Colchester': 'Colchester United',
  'Sutton': 'Sutton United',
  'Macclesfield FC': 'Macclesfield Town FC',
  'Barrow': 'Barrow AFC',
  'Notts Co': 'Notts County',
  'Yeovil': 'Yeovil Town',
  'Harrogate': 'Harrogate Town',
  'Crawley': 'Crawley Town',
  'Newport': 'Newport County',
  'Carlisle': 'Carlisle United',
  'Barnet': 'Barnet FC',
  'Forest Green': 'Forest Green Rovers',
  'Grimsby': 'Grimsby Town',
  'Salford': 'Salford City',
  'Stevenage': 'Stevenage FC',
  'Mansfield': 'Mansfield Town',
  'Hartlepool': 'Hartlepool United',
}

stadium_matches = {
    'Watford': 'Watford FC',
    'Fulham': 'Fulham FC',
    'Arsenal': 'Arsenal FC',
    'Burnley': 'Burnley FC',
    'Blackpool': 'Blackpool FC',
    'Chelsea': 'Chelsea FC',
    'Southampton': 'Southampton FC',
    'Everton': 'Everton FC',
    'Brentford': 'Brentford FC',
    'Liverpool': 'Liverpool FC',
    'Sunderland': 'Sunderland AFC',
    'Barnsley': 'Barnsley FC',
    'Millwall': 'Millwall FC',
    'Middlesbrough': 'Middlesbrough FC',
    'Reading': 'Reading FC',
    'Gillingham': 'Gillingham FC',
    'Port Vale': 'Port Vale FC',
    'Morecambe': 'Morecambe FC',
    'Bury': 'Bury AFC',
    'Portsmouth': 'Portsmouth FC',
    'Walsall': 'Walsall FC',
    'Chesterfield': 'Chesterfield FC',
    'Rochdale': 'Rochdale AFC',
    'Stevenage': 'Stevenage FC',
    'Macclesfield': 'Macclesfield FC',
    'Barnet': 'Barnet FC',
    'Barrow': 'Barrow AFC',
}